# Configuration file for codecov.io
# https://docs.codecov.io/docs/codecovyml-reference

codecov:
  branch: main
  bot: "codecov-io"
  ci:
    - "github.com"
  max_report_age: 24
  disable_default_path_fixes: no
  require_ci_to_pass: yes
  notify:
    # We have 4 versions of python, 3 dbt and 2 windows checks
    # So after 7 tests at least one python and one dbt check will
    # have run, meaning we should have accurate coverage
    after_n_builds: 7
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
