#############################
## GitHub Actions CI Tests ##
#############################
#
# This can be kicked off manually in the Actions tab of GitHub
# It will also run nightly at 2pm
# It will run on any pull request, except non-code changes
# (images, markdown files, )
#
name: CI Tests
on:
  workflow_dispatch:
  schedule:
    # 2am each night
    - cron: '00 2 * * *'
  pull_request:
  push:
    branches:
      - main
  merge_group:
    # Merge Queue checks requested. This feature is still in beta
    # from Github and so may need updating later.
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group
    types: [checks_requested]

jobs:

  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jobs: [ 'linting', 'doclinting', 'docbuild', 'yamllint' ]
    name: ${{ matrix.jobs }} tests
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - &install_tox_step name: Install dependencies
      shell: bash
      run: pip install tox
    - name: Run the tests
      run: tox -e ${{ matrix.jobs }}

  python-version-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # We don't enforce coverage on older Python versions.
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]
    name: Python ${{ matrix.python-version }} tests
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - *install_tox_step
    - name: Run the tests
      run: tox -e py -- -n 2 test

  python-version-tests-cov:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # We enforce coverage on this, the latest Python version.
        python-version: [ '3.11' ]
    name: Python ${{ matrix.python-version }} tests
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - *install_tox_step
    - name: Run the tests
      run: tox -e py -- --cov=sqlfluff -n 2 test
    - &codecov_coverage_step name: Upload Coverage (codecov)
      uses: codecov/codecov-action@v3
      with:
        # Public token to allow coverage from forks to work.
        token: fd44b020-c716-4f72-b5f3-03fa20119956
        files: ./coverage.xml
    - &coveralls_coverage_step name: Coveralls Parallel (coveralls)
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: coverage.lcov
        github-token: ${{ secrets.github_token }}
        flag-name: run-${{ matrix.python-version }}
        parallel: true
    - &github_coverage_step name: Upload coverage data (github)
      uses: actions/upload-artifact@v2
      with:
        name: coverage-data
        path: ".coverage.*"
        if-no-files-found: ignore

  other-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jobs: [ 'bench', 'mypy', 'doctests' ]
    name: ${{ matrix.jobs }} tests
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - *install_tox_step
    - name: Run the tests
      env:
        SQLFLUFF_BENCHMARK_API_KEY: ${{ secrets.SQLFLUFF_BENCHMARK_API_KEY }}
      run: |
        tox -e ${{ matrix.jobs }}

  examples:
    runs-on: ubuntu-latest
    name: example tests
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install -e .
        pip install tqdm
    - name: Test the example files
      run: |
        for file in examples/*
        do
          echo "Running $file"
          python "$file"
        done

  dbt-tests:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres: &postgres_service
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: password
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    strategy:
      matrix:
        # We don't enforce coverage on older dbt versions.
        dbt-version: [ 'dbt110' ]
    name: DBT Plugin ${{ matrix.dbt-version }} tests
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        # Use Python 3.10 rather than 3.9 due to this issue.
        # https://github.com/dbt-labs/dbt-core/issues/2827
        python-version: '3.9'
    - *install_tox_step
    - name: Run the tests
      run: |
        tox -e ${{ matrix.dbt-version }} -- plugins/sqlfluff-templater-dbt

  dbt-tests-cov:
    runs-on: ubuntu-latest
    services:
      postgres: *postgres_service
    strategy:
      matrix:
        # We enforce coverage on this, the latest dbt version.
        dbt-version: [ 'dbt140' ]
    name: DBT Plugin ${{ matrix.dbt-version }} tests
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - *install_tox_step
    - name: Run the tests
      run: |
        tox -e ${{ matrix.dbt-version }} -- --cov=sqlfluff_templater_dbt plugins/sqlfluff-templater-dbt
    - *codecov_coverage_step
    - *coveralls_coverage_step
    - *github_coverage_step

  python-windows-tests:
    runs-on: windows-latest
    name: Python 3.10 Windows tests
    steps:
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: List Env
      shell: bash
      run: |
        env | sort
    - *install_tox_step
    - name: Run the tests
      shell: bash
      # Set python temp dir in working dir as on GitHub Actions Windows
      # machine often has system temp dir (which tox uses) on C drive and
      # working dir on D drive which causes problems.
      run: |
        mkdir temp_pytest
        python -m tox -e winpy -- --cov=sqlfluff -n 2 test
    - *codecov_coverage_step
    - *github_coverage_step

  python-windows-dbt-tests:
    runs-on: windows-latest
    name: DBT Plugin Python 3.10 Windows tests
    steps:
    - name: Start PostgreSQL on Windows
      run: |
        $pgService = Get-Service -Name postgresql*
        Set-Service -InputObject $pgService -Status running -StartupType automatic
        Start-Process -FilePath "$env:PGBIN\pg_isready" -Wait -PassThru
    - name: Set postgres user password
      run: |
        & $env:PGBIN\psql --command="ALTER USER postgres PASSWORD 'password';" --command="\du"
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - *install_tox_step
    - name: Run the tests
      shell: bash
      # Do not set explicitly temp dir for dbt as causes problems
      # None of these test need temp dir set
      run: |
        python -m tox -e dbt140-winpy -- plugins/sqlfluff-templater-dbt

  pip-test-pull-request:
    # Test that using pip install works as we've missed
    # some dependencies in the past - see #1842
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    name: pip install tests
    steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        pip install .
    - name: Run the version test
      run: |
        sqlfluff --version
    - name: Run a simple select parse test via stdin
      run: |
        echo "select 1" | sqlfluff parse --dialect=ansi -
    - name: Run a simple select lint test via stdin
      run: |
        echo "select 1" | sqlfluff lint --dialect=ansi -
    - name: Run a simple select parse test via file
      run: |
        sqlfluff parse --dialect=ansi <(echo "select 1")
    - name: Run a simple select lint test via file
      run: |
        sqlfluff lint --dialect=ansi <(echo "select 1")

  coveralls_finish:
    needs: [python-version-tests-cov, dbt-tests-cov, python-windows-tests]
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true

  coverage_check:
    name: Combine & check coverage.
    runs-on: ubuntu-latest
    needs: [python-version-tests-cov, dbt-tests-cov, python-windows-tests]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - run: python -m pip install --upgrade coverage[toml]

      - name: Download coverage data.
        uses: actions/download-artifact@v2
        with:
          name: coverage-data

      - name: Combine coverage & fail if it's <100%.
        run: |
          python -m coverage combine
          python -m coverage html --skip-covered --skip-empty
          python -m coverage report --fail-under=100

      - name: Upload HTML report if check failed.
        uses: actions/upload-artifact@v2
        with:
          name: html-report
          path: htmlcov
        if: ${{ failure() }}
