#############################
## GitHub Actions CI Tests ##
#############################
#
# This is a reusable workflow to make CI tests more modular.
# See: https://docs.github.com/en/actions/using-workflows/reusing-workflows
#
# Called by ci-tests.yml
# This one does the python tests
#

name: Modular SQLFluff python test workflow

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      coverage:
        required: false
        type: boolean
        default: false
    secrets:
      gh_token:
        required: true

jobs:
  modular-python-test:
    runs-on: ubuntu-latest
    name: py${{ inputs.python-version }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: pip install tox

    - name: Parse Python Version
      id: py_version
      run: |
        PYVERSION=$(echo "${{ matrix.python-version }}" | sed -e 's/\.//g')
        echo "PYVERSION=$PYVERSION" >> $GITHUB_OUTPUT

    - name: Run the tests (with coverage)
      if: ${{ inputs.coverage }}
      run: tox -e py${{ steps.py_version.outputs.PYVERSION }} -- --cov=sqlfluff -n 2 test

    - name: Run the tests (without coverage)
      if: ${{ !inputs.coverage }}
      run: tox -e py${{ steps.py_version.outputs.PYVERSION }} -- -n 2 test

    - name: Coveralls Parallel (coveralls)
      uses: coverallsapp/github-action@master
      if: ${{ inputs.coverage }}
      with:
        path-to-lcov: coverage.lcov
        github-token: ${{ secrets.gh_token }}
        flag-name: run-${{ inputs.python-version }}
        parallel: true

    - name: Upload coverage data (github)
      uses: actions/upload-artifact@v2
      if: ${{ inputs.coverage }}
      with:
        name: coverage-data
        path: ".coverage.*"
        if-no-files-found: ignore
