name: Create release pull request

on:
  workflow_dispatch:
    inputs:
      newVersionNumber:
        description: 'New version number'
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Replace version
        run: |
          sed -i -e '/version =/ s/= .*/= ${{ github.event.inputs.newVersionNumber }}/' ./plugins/sqlfluff-templater-dbt/setup.cfg
          sed -i -e '/version =/ s/= .*/= ${{ github.event.inputs.newVersionNumber }}/' ./setup.cfg
          sed -i -e '/stable_version =/ s/= .*/= ${{ github.event.inputs.newVersionNumber }}/' ./setup.cfg

      - name: Start Changelog entry
        run: |
          RELEASE_LIST=$(gh release list)
          echo $RELEASE_LIST
          LATEST_DRAFT_RELEASE=$(echo $RELEASE_LIST | grep Draft | head -n1 | awk '{print $1;}')
          echo $LATEST_DRAFT_RELEASE
          echo "" > notes.txt
          echo "##[${{ github.event.inputs.newVersionNumber }}] - $(date +%F)" >> notes.txt
          echo "" >> notes.txt
          echo "## Highlights" >> notes.txt
          echo "" >> notes.txt
          gh release view $LATEST_DRAFT_RELEASE | sed '1,/^--$/d' >> notes.txt
          echo "" >> notes.txt
          echo "## New Contributors" >> notes.txt
          cat notes.txt
          sed -i -e '/DO NOT DELETE THIS LINE/r./notes.txt' CHANGELOG.md
          rm notes.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          delete-branch: true
          branch: prep-${{ github.event.inputs.newVersionNumber }}
          commit-message: "Bump to version ${{ github.event.inputs.newVersionNumber }}"
          title: Prep version ${{ github.event.inputs.newVersionNumber }}
          body: |
            Prepare version ${{ github.event.inputs.newVersionNumber }}

            Please add all merged changes from [Release Draft][1] to
            the CHANGELOG.md file

            - Auto-generated by [create-pull-request][2] GitHub Action

            [1]: https://github.com/sqlfluff/sqlfluff/releases
            [2]: https://github.com/peter-evans/create-pull-request
          labels: release
